spring:
  cloud:
    gateway:
      routes:
        - id: GENERAL-INFORMATION-SERVICE
          predicates:
            - Path=/general-information/**
          uri: "lb://GENERAL-INFORMATION-SERVICE"
        - id: OFFER-SERVICE
          predicates:
            - Path=/offer/**
          uri: "lb://OFFER-SERVICE"
        - id: MAIL-SERVICE
          predicates:
            - Path=/mail/**
          uri: "lb://MAIL-SERVICE"

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PATCH
              - DELETE
              - PUT
            allowedHeaders:
              - Content-Type





